#!/bin/bash

MYSQL_CONFIG=/etc/my.cnf
MYSQL_DATADIR=/var/lib/mysql/data

function mysql_create_dir() {
    local dir="$1"; shift

    mkdir -p "${dir}"
    chown mysql:0 "${dir}"
    chmod 0700 "${dir}"
}


mysql_create_dir "${MYSQL_CONFIG}.d"
rm -f "${MYSQL_CONFIG}.d"/*

cat > "${MYSQL_CONFIG}" <<EOCONF
[mysqld]

# Disabling symbolic-links is recommended to prevent assorted security risks
symbolic-links = 0

# http://www.percona.com/blog/2008/05/31/dns-achilles-heel-mysql-installation/
skip_name_resolve

!includedir ${MYSQL_CONFIG}.d
EOCONF

mysql_create_dir "${MYSQL_DATADIR}"

unset MYSQL_CONFIG
unset MYSQL_DATADIR
unset mysql_create_dir
